### ISSUE TITLE
Is this plugin abandoned?

### ISSUE THREAD

**Issue by emmgfx** [kmoskwiak/videojs-resolution-switcher#102]
Last commit is from more than a year ago, and actually seems that doesn't work well on the latest versions of videojs. Is this plugin abandoned?

**Comment by Gataquadrada** [comment]
As mentioned [here](https://github.com/videojs/video.js/wiki/Plugins), this plugin only works with Video.JS 5.
So, yeah, I'd consider that as "abandoned".

EDIT: I know. Iknow. Almost a year after the original question. 
But people may come here searching for answers.

**Comment by npstcole** [comment]
Does anyone know of a branch for using with videoJS version 6+?

**Comment by Gataquadrada** [comment]
@npstcole I went with a custom solution. 
I added a custom [button](https://docs.videojs.com/button) and used jQuery to show a custom popup that changes the [src](https://docs.videojs.com/html5#src) based on what quality the user chooses.

You can see the result [here](http://www.finepixel.com.br/cursos-online/?fx_pe_curso=3&fx_pe_aula=64).

EDIT: Changing the src will trigger every event set to fire on video load.

**Comment by npstcole** [comment]
Thanks, I use something very similar for AD videos using a custom button as well. The problem I'm going to run into is that we now need to add playlists to this and I'm looking for a way to modify the existing code to work since playlists don't seem to support multiple resolutions out of the box. This has me hunting down a rabbit hole of upgrading from 5.x to 6+ researching possibilities for off the shelf solutions. We have A LOT going on as you can see [here](https://www.nps.gov/media/video/view.htm?id=30E162BF-1DD8-B71B-0B693690B59C2198)

**Comment by Gataquadrada** [comment]
Well, the best way to overcome something is to go through it.
I updated from 5.x to 6.x and have no regrets. A lot of stuff is just plain easier than before.
Adding a button (solving my case, in general) was a matter of 5 lines of code, with 6.x.
